services:
  - type: web
    name: cse341-community-service-connect
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: DB_NAME
        value: community_service_connect
      - key: SESSION_SECRET
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: GITHUB_CALLBACK_URL
        sync: false
